"use client";

import { useState, useEffect, useCallback } from "react";
import { ArrowUp, X } from "lucide-react";
import { motion, AnimatePresence } from "motion/react";

import type { RegistryEntry } from "@/registry";

const categoryMessages: Record<string, { user: string; ai: string }> = {
  composer: {
    user: "Build a rich prompt input for our AI assistant",
    ai: "Here's a composer with file attachments, slash commands, and @mentions ready to drop in.",
  },
  loaders: {
    user: "What should we show while the AI generates a response?",
    ai: "This loading indicator keeps users informed without breaking the conversation flow.",
  },
  traces: {
    user: "How do we surface the agent's reasoning to users?",
    ai: "This trace component shows each step as the agent reasons through the problem.",
  },
  agents: {
    user: "How should users manage agent configurations?",
    ai: "Here's a pattern for surfacing agent controls at the right moment in the flow.",
  },
  messages: {
    user: "Show me how conversation messages should look.",
    ai: "Here's a message component with edit, copy, and feedback actions built in.",
  },
  buttons: {
    user: "What's the right button for stopping AI generation?",
    ai: "This button morphs between states to give users clear control over generation.",
  },
  code: {
    user: "How should I display code changes generated by the AI?",
    ai: "Here's a diff viewer that makes AI-generated code changes easy to review.",
  },
  errors: {
    user: "How do we show AI errors without losing the user's context?",
    ai: "This error card keeps users informed while offering a clear path forward.",
  },
  text: {
    user: "How should selected text interact with AI actions?",
    ai: "This pattern surfaces contextual AI actions right where the user is working.",
  },
  voice: {
    user: "How do we add voice input to our AI product?",
    ai: "Here's a dictation component with recording state and waveform feedback.",
  },
  navigation: {
    user: "How should command search work in an AI-first product?",
    ai: "This command palette lets users access AI actions and content fast.",
  },
  permissions: {
    user: "How do we ask users to approve sensitive AI actions?",
    ai: "Here's a permission prompt that's clear about what the AI wants to do and why.",
  },
  flowcharts: {
    user: "How can we visualize the agent's decision process?",
    ai: "This flowchart shows the agent's logic as it picks tools and routes tasks.",
  },
  indicators: {
    user: "How do we signal that the AI is live and connected?",
    ai: "This indicator shows agent status without distracting from the main flow.",
  },
  compare: {
    user: "How should users compare AI-generated responses?",
    ai: "This comparison view lets users evaluate multiple outputs side by side.",
  },
  uploads: {
    user: "How do I show file attachments in the composer?",
    ai: "This attachment chip shows upload progress and file previews clearly.",
  },
  collaboration: {
    user: "How do we show connected data sources in the AI flow?",
    ai: "This connector panel surfaces available integrations at the right moment.",
  },
  access: {
    user: "How do we handle access control in an agent product?",
    ai: "Here's a pattern for surfacing and managing access permissions clearly.",
  },
};

function getMessages(entry: RegistryEntry) {
  const convo = categoryMessages[entry.category];
  if (convo) return convo;
  return {
    user: `Add a ${entry.title.toLowerCase()} to our AI product`,
    ai: entry.description,
  };
}

export function PatternDrawer({
  entry,
  onClose,
}: {
  entry: RegistryEntry;
  onClose: () => void;
}) {
  const [visible, setVisible] = useState(true);
  const { user: userMsg, ai: aiMsg } = getMessages(entry);
  const Demo = entry.Demo;

  const close = useCallback(() => {
    setVisible(false);
    setTimeout(onClose, 320);
  }, [onClose]);

  useEffect(() => {
    function onKeyDown(e: KeyboardEvent) {
      if (e.key === "Escape") close();
    }
    document.addEventListener("keydown", onKeyDown);
    return () => document.removeEventListener("keydown", onKeyDown);
  }, [close]);

  return (
    <AnimatePresence>
      {visible && (
        <>
          <motion.div
            key="backdrop"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.2 }}
            className="fixed inset-0 z-40 bg-black/40 backdrop-blur-sm"
            onClick={close}
          />
          <motion.div
            key="panel"
            initial={{ x: "100%" }}
            animate={{ x: 0 }}
            exit={{ x: "100%" }}
            transition={{ type: "spring", damping: 28, stiffness: 280 }}
            className="fixed inset-y-0 right-0 z-50 flex w-full max-w-2xl flex-col bg-background shadow-2xl"
          >
            <div className="flex shrink-0 items-center justify-between border-b px-6 py-4">
              <div className="flex items-center gap-2 min-w-0">
                <p className="text-xs font-medium uppercase tracking-wider text-muted-foreground shrink-0">
                  {entry.category}
                </p>
                <span className="text-muted-foreground/40 text-xs">/</span>
                <h2 className="truncate text-sm font-semibold">{entry.title}</h2>
              </div>
              <button
                type="button"
                onClick={close}
                className="ml-4 shrink-0 rounded-md p-1.5 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
              >
                <X className="size-4" />
                <span className="sr-only">Close</span>
              </button>
            </div>

            <div className="flex-1 overflow-y-auto px-6 py-8 space-y-6">
              <div className="flex justify-end">
                <div className="max-w-[75%] rounded-2xl bg-primary px-4 py-2.5 text-sm leading-relaxed text-primary-foreground">
                  {userMsg}
                </div>
              </div>

              <div className="flex flex-col gap-4">
                <div className="max-w-[75%] rounded-2xl bg-muted px-4 py-2.5 text-sm leading-relaxed text-foreground">
                  {aiMsg}
                </div>
                <div className="flex items-center justify-center rounded-2xl border bg-muted/20 p-8">
                  <Demo />
                </div>
              </div>
            </div>

            <div className="shrink-0 border-t px-4 py-3">
              <div className="flex items-center gap-3 rounded-xl border bg-muted/40 px-4 py-2.5">
                <span className="flex-1 text-sm text-muted-foreground/60 select-none">
                  Ask a follow-up...
                </span>
                <div className="flex size-6 items-center justify-center rounded-full bg-primary/20 text-primary">
                  <ArrowUp className="size-3.5" />
                </div>
              </div>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}
