#!/usr/bin/env node
// Regenerates the bundled reference material for the `ai-patterns` skill
// (plugins/ai-patterns/skills/design/reference/**) from src/registry/**.
//
// The registry (src/registry/index.ts + each <category>/<slug>/pattern.ts
// and component.tsx) is the single source of truth. This script never
// hand-writes pattern content — it only extracts and reformats what's
// already there, so re-running it after adding a pattern is the entire
// "keep the skill in sync" workflow.
//
// Usage: node scripts/build-skill.mjs   (or: npm run skill:build)

import { readFileSync, writeFileSync, mkdirSync, readdirSync, rmSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const registryDir = join(repoRoot, "src/registry");
const referenceDir = join(repoRoot, "plugins/ai-patterns/skills/design/reference");

function parseRegistryEntries() {
  const indexSource = readFileSync(join(registryDir, "index.ts"), "utf8");
  const arrayMatch = indexSource.match(/export const registry: RegistryEntry\[\] = \[([\s\S]*?)\n\];/);
  if (!arrayMatch) {
    throw new Error("Could not find `export const registry: RegistryEntry[] = [...]` in src/registry/index.ts");
  }

  // (?:[^"\\]|\\.)* matches a JS string body, letting an escaped quote
  // (e.g. the \"Thought for Xs\" inside Expandable Trace's description)
  // pass through instead of ending the match early.
  const field = (name) => new RegExp(`${name}:\\s*"((?:[^"\\\\]|\\\\.)*)"`);
  const unescape = (s) => s.replace(/\\"/g, '"').replace(/\\\\/g, "\\");

  const entries = [];
  const objectBlocks = arrayMatch[1].match(/\{\s*slug:[\s\S]*?\n {2}\},/g) ?? [];
  for (const block of objectBlocks) {
    const slug = block.match(field("slug"))?.[1];
    const category = block.match(field("category"))?.[1];
    const version = block.match(field("version"))?.[1];
    const title = block.match(field("title"))?.[1];
    const description = block.match(field("description"))?.[1];
    if (!slug || !category || !version || !title || !description) {
      throw new Error(`Could not parse a registry entry from block:\n${block}`);
    }
    entries.push({ slug, category, version, title: unescape(title), description: unescape(description) });
  }
  if (entries.length === 0) {
    throw new Error("Parsed zero registry entries — check the regex against the current index.ts shape.");
  }
  return entries;
}

function extractUxDoc(patternTsSource) {
  const match = patternTsSource.match(/export const pattern = `([\s\S]*)`;\s*$/);
  if (!match) {
    throw new Error("Could not find `export const pattern = `...`;` in pattern.ts");
  }
  return match[1].replace(/\\`/g, "`").trim();
}

function buildPatternDoc(entry) {
  const dir = join(registryDir, entry.category, entry.slug);
  const uxDoc = extractUxDoc(readFileSync(join(dir, "pattern.ts"), "utf8"));
  const componentSource = readFileSync(join(dir, "component.tsx"), "utf8").trim();

  return `<!-- GENERATED by scripts/build-skill.mjs from src/registry/${entry.category}/${entry.slug}/. Do not hand-edit; edit the registry and re-run \`npm run skill:build\`. -->

**category:** ${entry.category} · **slug:** \`${entry.slug}\` · **version:** ${entry.version}

If you already scaffolded this pattern from an earlier install of this skill
and its **version** here has a higher major number than what you used before,
its props changed in a breaking way — re-check the spec and this
implementation against your usage before assuming the old code still applies.

${uxDoc}

## Default implementation (Tailwind v4 + Radix + Motion)

This is the catalogue's own reference implementation — use it verbatim when the
host project has no established design system, or when the user asks for
"the demoed look." When the host project has its own design system, treat
this code as a translation reference: keep every rule from the spec above
(Anatomy, Behavior, Content guidelines, Accessibility) and re-express the
markup, styling, and motion using that system's own components/tokens
instead of copying these Tailwind classes or the Motion API.

\`\`\`tsx
${componentSource}
\`\`\`
`;
}

function buildIndex(entries) {
  const byCategory = new Map();
  for (const entry of entries) {
    if (!byCategory.has(entry.category)) byCategory.set(entry.category, []);
    byCategory.get(entry.category).push(entry);
  }

  const cell = (s) => s.replace(/\|/g, "\\|");

  const rows = [...byCategory.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([category, categoryEntries]) => {
      const lines = categoryEntries
        .sort((a, b) => a.slug.localeCompare(b.slug))
        .map((e) => `| \`${e.slug}\` | ${e.version} | ${cell(e.title)} | ${cell(e.description)} | [${e.category}/${e.slug}.md](./${e.category}/${e.slug}.md) |`)
        .join("\n");
      return `### ${category}\n\n| slug | version | title | description | spec |\n| --- | --- | --- | --- | --- |\n${lines}`;
    })
    .join("\n\n");

  return `<!-- GENERATED by scripts/build-skill.mjs from src/registry/index.ts. Do not hand-edit; edit the registry and re-run \`npm run skill:build\`. -->

# Pattern index (${entries.length} patterns)

Shortlist candidates from this table, then open the linked spec file for any
pattern before recommending or scaffolding it — this table only has the
one-line description, not the Anatomy/Behavior/Accessibility contract.

${rows}
`;
}

function main() {
  const entries = parseRegistryEntries();

  // Wipe and rebuild so removed/renamed patterns don't leave stale files behind.
  rmSync(referenceDir, { recursive: true, force: true });
  mkdirSync(referenceDir, { recursive: true });

  writeFileSync(join(referenceDir, "index.md"), buildIndex(entries));

  for (const entry of entries) {
    const outDir = join(referenceDir, entry.category);
    mkdirSync(outDir, { recursive: true });
    writeFileSync(join(outDir, `${entry.slug}.md`), buildPatternDoc(entry));
  }

  console.log(`Built reference material for ${entries.length} patterns into ${referenceDir}`);
  for (const entry of entries) {
    console.log(`  - ${entry.category}/${entry.slug}`);
  }
}

main();
